# Generated by Django 5.0.4 on 2024-12-15 15:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applications',
            fields=[
                ('application_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('initials', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^(\\+?\\d{0,4})?\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{4}\\)?)?$', 'The phone number provided is invalid')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('comments', models.TextField(verbose_name='Комментарии')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки заявки')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Заявки',
                'ordering': ('initials',),
            },
        ),
        migrations.CreateModel(
            name='blocks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dateUpdate', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('weight', models.PositiveIntegerField(verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Блоки',
                'verbose_name_plural': 'Блоки',
                'ordering': ('weight',),
            },
        ),
        migrations.CreateModel(
            name='moviesModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('fileName', models.FileField(upload_to='', verbose_name='Файл')),
                ('formatVideo', models.CharField(choices=[('horizontal', 'Горизонтальное'), ('vertical', 'Вертикальное'), ('quadratic', 'Квадратное')], default='Горизонтальное', max_length=50, verbose_name='Формат файла')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dateUpdate', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('weight', models.PositiveIntegerField(verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ('weight',),
            },
        ),
        migrations.CreateModel(
            name='projectsFilesModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('fileName', models.FileField(upload_to='', verbose_name='Файл')),
                ('format', models.CharField(choices=[('horizontal', 'Горизонтальное'), ('vertical', 'Вертикальное'), ('quadratic', 'Квадратное')], default='Горизонтальное', max_length=50, verbose_name='Формат файла')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dateUpdate', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('weight', models.PositiveIntegerField(verbose_name='Сортировка')),
                ('projectsId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.moviesmodel', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
                'ordering': ('weight',),
            },
        ),
    ]
