# Generated by Django 5.0.4 on 2024-12-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='sphere_activity',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Сфера деятельности'),
        ),
        migrations.AddField(
            model_name='applications',
            name='url_links',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Соц. сети организации'),
        ),
    ]
