# Generated by Django 5.0.4 on 2024-12-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsfilesmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Проект'),
        ),
    ]
