# Generated by Django 5.0.4 on 2024-12-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_applications_sphere_activity_applications_url_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='company',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Заголовок'),
        ),
    ]
