# Generated by Django 5.0.4 on 2024-12-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_photomodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviesmodel',
            options={'ordering': ('weight',), 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterModelOptions(
            name='photomodel',
            options={'ordering': ('weight',), 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.RemoveField(
            model_name='photomodel',
            name='formatVideo',
        ),
        migrations.AddField(
            model_name='photomodel',
            name='formatPhoto',
            field=models.CharField(choices=[('horizontal', 'Горизонтальное'), ('vertical', 'Вертикальное')], default='URL в млг не найден', max_length=50),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='dateUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='formatVideo',
            field=models.CharField(choices=[('horizontal', 'Горизонтальное'), ('vertical', 'Вертикальное')], default='URL в млг не найден', max_length=50),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='dateUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
