# Generated by Django 5.0.4 on 2024-12-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_projectsfilesmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsfilesmodel',
            options={'ordering': ('weight',), 'verbose_name': 'Проектные файлы', 'verbose_name_plural': 'Проектные файлы'},
        ),
        migrations.AddField(
            model_name='moviesmodel',
            name='limit_keys',
            field=models.PositiveIntegerField(default=5, verbose_name='Количество файлов в проекте'),
        ),
        migrations.AlterField(
            model_name='projectsfilesmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
