# Generated by Django 5.0.4 on 2024-12-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_moviesmodel_options_alter_photomodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='dateUpdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='fileName',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='formatVideo',
            field=models.CharField(choices=[('horizontal', 'Горизонтальное'), ('vertical', 'Вертикальное')], default='URL в млг не найден', max_length=50, verbose_name='Формат видео'),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='weight',
            field=models.PositiveIntegerField(verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='dateUpdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='fileName',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='formatPhoto',
            field=models.CharField(choices=[('horizontal', 'Горизонтальное'), ('vertical', 'Вертикальное')], default='URL в млг не найден', max_length=50, verbose_name='Формат фото'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='weight',
            field=models.PositiveIntegerField(verbose_name='Сортировка'),
        ),
    ]
