# Generated by Django 5.0.4 on 2024-12-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_projectsfilesmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='limit_keys',
            field=models.PositiveIntegerField(default=5, verbose_name='Лимит файлов в проекте'),
        ),
    ]
