# Generated by Django 5.0.4 on 2024-12-17 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_applications_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='url_links',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Соц. сети организации'),
        ),
    ]
