# Generated by Django 5.0.4 on 2025-01-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_applications_url_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ('dateCreated',), 'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='blocks',
            name='description_en',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='blocks',
            name='title_en',
            field=models.CharField(default='', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='moviesmodel',
            name='description_en',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='moviesmodel',
            name='title_en',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='initials',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
