# Generated by Django 5.0.4 on 2025-01-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_applications_options_blocks_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='description_en',
            field=models.TextField(default='', verbose_name='Описание  (англ.)'),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='title_en',
            field=models.CharField(default='', max_length=255, verbose_name='Заголовок  (англ.)'),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='description_en',
            field=models.TextField(default='', verbose_name='Описание  (англ.)'),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='title_en',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Заголовок (англ.)'),
        ),
    ]
