# Generated by Django 5.0.4 on 2024-12-13 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_moviesmodel_backend_mov_weight_896ee1_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='applications',
            fields=[
                ('application_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('initials', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^(\\+?\\d{0,4})?\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{4}\\)?)?$', 'The phone number provided is invalid')])),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('comments', models.TextField(verbose_name='Комментарии')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки заявки')),
            ],
        ),
    ]
