# Generated by Django 5.0.4 on 2024-12-13 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_applications_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ('application_id',), 'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='applications',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^(\\+?\\d{0,4})?\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{4}\\)?)?$', 'The phone number provided is invalid')], verbose_name='Телефон'),
        ),
    ]
