version: "3.3"

services:
  frontend:
    build: ./front/
    container_name: frontend
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./front:/front/
      - node_modules:/front/node_modules
    networks:
      - vite-network

  backend:
    build: ./back
    container_name: backend
    volumes:
      - ./back:/back/
    ports:
      - "8001:8001"
    networks:
      - vite-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:8080"  # Пробрасываем порт 80 на 8080, который используется в конфигурации Nginx
    volumes:
      - ./front/nginx.conf:/etc/nginx/conf.d/default.conf  # Подключаем конфигурацию Nginx
      - ./front:/usr/share/nginx/html  # Подключаем фронтенд
      - ./back/digitalCulture/media:/usr/share/nginx/media  # Проброс папки media
      - ./back/digitalCulture/static:/usr/share/nginx/static  # Проброс папки static
      - ./ssl/digitalCulture.pem:/etc/ssl/certs/fullchain.pem  # SSL сертификат
      - ./ssl/digitalCulturePrivate.pem:/etc/ssl/private/privkey.pem  # Закрытый ключ
    networks:
      - vite-network

networks:
  vite-network:
    driver: bridge

volumes:
  node_modules: {}
