version: "3.3"

services:
  frontend:
    build: ./front/
    ports:
      - "3000:3000"
    volumes:
      - ./front:/front/
      
  backend:
    build: ./back
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./back:/back/
    ports:
      - "8001:8001"