version: "3.3"

services:
  frontend:
    # restart: always
    build: ./front/
    container_name: frontend
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./front:/front/
      - ./front/node_modules:/front/node_modules
    networks:
      - vite-network

  backend:
    # restart: always
    build: ./back
    container_name: backend
    volumes:
      - ./back:/back/
      - ./back/digitalCulture/media/:/back/media
      - ./back/digitalCulture/static:/back/static
    ports:
      - "8001:8001"
    networks:
      - vite-network

networks:
  vite-network:
    driver: bridge


volumes:
  static:
    driver: local
  media:
    driver: local
