version: "3.3"

services:
  frontend:
    build: ./front/
    ports:
      - "4173:4173"
    volumes:
      - ./front:/front/
      - node_modules:/front/node_modules
    networks:
      - vite-network
      
  backend:
    build: ./back
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./back:/back/
    ports:
      - "8001:8001"

networks:
  vite-network:
    driver: bridge

volumes:
  node_modules: {}