# Generated by Django 5.0.4 on 2024-12-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_moviesmodel_datecreated_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='moviesmodel',
            index=models.Index(fields=['weight'], name='backend_mov_weight_896ee1_idx'),
        ),
    ]
