# Generated by Django 5.0.4 on 2024-12-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_moviesmodel_backend_mov_weight_896ee1_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='moviesmodel',
            name='backend_mov_weight_896ee1_idx',
        ),
    ]
