# Generated by Django 5.0.4 on 2024-12-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_applications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ('initials',), 'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
    ]
